name = "Test"
uuid = "e6038f6e-b188-4f2e-b929-9960538f95c7"
repo = "https://github.com/JuliaRegistries/Test.git"

description = """
Registry for testing purposes only.
"""

[packages]
7876af07-990d-54b4-ab0e-23690620f79a = { name = "Example", path = "E/Example" }
